# Generated by Django 4.0.6 on 2022-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Ceremony Choice',
                'verbose_name_plural': 'Ceremony Choices',
            },
        ),
        migrations.RemoveField(
            model_name='ceremonies',
            name='ceremonies',
        ),
        migrations.AddField(
            model_name='ceremonies',
            name='ceremonies',
            field=models.ManyToManyField(to='profiles.ceremonychoices', verbose_name='Ceremonies'),
        ),
    ]
