# Generated by Django 4.0.6 on 2022-07-15 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_extended',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subs_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='Ceremonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_date', models.DateTimeField(blank=True)),
                ('ceremonies', models.CharField(choices=[('DS', 'Daily Scrum'), ('SP', 'Sprint Planning'), ('SR', 'Sprint Review'), ('SRET', 'Sprint Retrospective'), ('BLR', 'Backlog Refinement')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cer_date'],
            },
        ),
    ]
