# Generated by Django 4.0.6 on 2022-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_ceremonychoices_remove_ceremonies_ceremonies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonies',
            name='ceremonies',
        ),
        migrations.AddField(
            model_name='ceremonies',
            name='ceremonies',
            field=models.CharField(default=1, help_text='You can select more than 1 option', max_length=50),
            preserve_default=False,
        ),
    ]
