# Generated by Django 4.0.6 on 2022-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_date_extended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_extended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subs_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
