# Generated by Django 4.0.6 on 2022-07-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_ceremonies_ceremonies_ceremonies_ceremonies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeremonyChoices',
        ),
    ]
