# Generated by Django 4.0.6 on 2022-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_ceremonychoices_ceremonies_has_facilitated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonies',
            name='has_facilitated',
        ),
        migrations.AddField(
            model_name='ceremonychoices',
            name='has_facilitated',
            field=models.BooleanField(default=False),
        ),
    ]
