# Generated by Django 4.0.6 on 2022-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_ceremonies_has_facilitated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceremonies',
            options={'ordering': ['-cer_date'], 'verbose_name': 'Ceremony', 'verbose_name_plural': 'Ceremonies'},
        ),
        migrations.AlterModelOptions(
            name='ceremonychoices',
            options={'verbose_name': 'Ceremony Choice', 'verbose_name_plural': 'Ceremony Choices'},
        ),
        migrations.RemoveField(
            model_name='ceremonychoices',
            name='has_facilitated',
        ),
        migrations.AlterField(
            model_name='ceremonies',
            name='cer_date',
            field=models.DateTimeField(blank=True, verbose_name='Date of Ceremony'),
        ),
        migrations.AlterField(
            model_name='ceremonies',
            name='ceremonies',
            field=models.ManyToManyField(to='profiles.ceremonychoices', verbose_name='Ceremonies'),
        ),
    ]
